# Generated by Django 3.1.3 on 2020-11-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msahomeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='username',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
