# Generated by Django 3.1.3 on 2020-12-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msahomeapp', '0002_referee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_detail',
            field=models.TextField(blank=True, default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='player_redcards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_yellowcards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='email',
            field=models.EmailField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='score',
            name='match_detail',
            field=models.TextField(blank=True, default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='score',
            name='referee_comment',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
